# Generated by Django 5.1.2 on 2025-03-27 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the city for which weather data is available.', max_length=100, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the city was added to the database.')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Recorded temperature in Celsius.')),
                ('condition', models.CharField(help_text='Short description of the current weather condition.', max_length=100)),
                ('icon_url', models.URLField(blank=True, help_text='URL for a weather icon image (optional).', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Timestamp for the last update of this weather report.')),
                ('city', models.ForeignKey(help_text='Foreign key linking this weather report to a city.', on_delete=django.db.models.deletion.CASCADE, related_name='weather_reports', to='weather.city')),
            ],
        ),
    ]
