# Generated by Django 5.1.7 on 2025-03-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherreport',
            name='icon_url',
            field=models.URLField(blank=True, help_text='URL for a weather icon image.', null=True),
        ),
    ]
